# Generated by Django 3.1.7 on 2021-04-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('unit', models.CharField(max_length=64, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена в у.е.')),
                ('date', models.DateField(verbose_name='Дата последнего поступления')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'ресурсы',
            },
        ),
    ]
