# Generated by Django 3.1.7 on 2021-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='price',
            field=models.IntegerField(verbose_name='Цена в у.е.'),
        ),
    ]
